microsoft/AzureDevOpsDemoGenerator

README.md

Fixed broken link for custom templates

Fixed broken link for custom templates

---

README.md
docs/Using-The-Template-Extractor.md

Broken links from README page fixed. Broken image links and back to previous link in Extractor docs fixed.

Fixed a few broken links and image refs.

---

README.md

Fixed the link of the doc page  "Creating custom templates"

Fixed the link of the doc page

---

src/VstsDemoBuilder/Scripts/AppScripts/create.js

scripting changes

---

src/VstsDemoBuilder/Templates/MyHealthClinic/BuildDefinitions/MyHealthClinic.Web.json

Fixed issue with MHC pipeline [Issue](https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/194)

MHC build corrections

---

src/VstsDemoBuilder/Scripts/AppScripts/create.js
src/VstsDemoBuilder/Templates/ContosoAir/ReleaseDefinitions/ContosoAirRelease.json

[AB#3316](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3316)

corrected contoso air template release definition AB#3316

---

src/VstsDemoBuilder/PreSetting/ProjectSettings.json
src/VstsDemoBuilder/Templates/TemplateImages/mslearn/deploy-azure-functions.svg
src/VstsDemoBuilder/Templates/TemplateSetting.json
src/VstsDemoBuilder/Templates/deploy-docker-template/ProjectSettings.json
src/VstsDemoBuilder/Templates/deploy-kubernetes-template/ProjectSettings.json
src/VstsDemoBuilder/VstsDemoBuilder.csproj

Closes #239 closes #242 
[AB#3380](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3380) [AB#3375](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3375) [AB#3376](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3376)

changes to user assignment and updated MSL template #239 #242

---

src/VstsDemoBuilder/Templates/DeploymentGroups/BuildDefinitions/DeploymentGroups.json
src/VstsDemoBuilder/Templates/DeploymentGroups/ReleaseDefinitions/DeploymentGroups.json
src/VstsRestAPI/WorkItemAndTracking/ImportWorkItems.cs

In this commit i have corrected Deployment groups pipeline corrections and work item assignment to the right team area for delivery plans templates

Pipeline correction and work item assignment correction

---

src/VstsDemoBuilder/Controllers/EnvironmentController.cs
src/VstsDemoBuilder/Views/Environment/CreateProject.cshtml

In this commit I have fixed extension validation issue for private templates.

fixed extension validation issue for private template AB#3415

---

src/VstsDemoBuilder/Templates/TemplateImages/mslearn/deploy-docker.svg
src/VstsDemoBuilder/Templates/TemplateImages/mslearn/deploy-kubernetes.svg
src/VstsDemoBuilder/Templates/TemplateSetting.json
src/VstsDemoBuilder/VstsDemoBuilder.csproj

In this PR i have added template icons for MS Learn templates

added MSL Icons

---

src/VstsDemoBuilder/Templates/CloudAdoptionPlan/WorkItems/Epic.json
src/VstsDemoBuilder/Templates/CloudAdoptionPlan/WorkItems/Feature.json

Re-ordered work items [AB#3443](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3443)

Cloud adoption plan template - work item re-ordered in JSON file to fix the ordering 

---

.github/workflows/codeql.yml

Hello! Thank you for being one of our early adopters on CodeQL. We've updated some of our best practices around when to run, so I'm proposing a quick change that reduces  how often it runs to reduce the compute minutes used. This won't have any functional impact, in fact, you'll start to get scans against pull requests from forks as well. 
Let me know if you have any questions on this!

Update CodeQL to latest best practices

---

src/AzureDevOpsDemoBuilder/Models/Project.cs
src/AzureDevOpsDemoBuilder/Services/ExtractorService.cs
src/AzureDevOpsDemoBuilder/Services/ProjectService.cs
src/AzureDevOpsDemoBuilder/Views/Environment/CreateProject.cshtml
src/AzureDevOpsDemoBuilder/wwwroot/Scripts/AppScripts/Extractor.js
src/AzureDevOpsDemoBuilder/wwwroot/Scripts/AppScripts/GitHubAuth.js
src/AzureDevOpsDemoBuilder/wwwroot/Scripts/AppScripts/create.js
src/AzureDevOpsDemoBuilder/wwwroot/Templates/CreateGitHubRepo.json
src/AzureDevOpsDemoBuilder/wwwroot/Templates/TemplateSetting.json
src/AzureDevOpsDemoBuilder/wwwroot/Templates/create-build-pipeline/ImportSourceCode/GitRepository.json
src/AzureDevOpsRestApi/ApiServiceBase.cs
src/AzureDevOpsRestApi/Git/GitHubImportRepo.cs
src/AzureDevOpsRestApi/Git/ImportRepoResponse.cs
src/AzureDevOpsRestApi/Viewmodel/GitHub/GitHubRepos.cs

Importing GitHub Repository has been implemented and it is available for only one template in MS Learn nav. Here is the direct link for [test slot](https://demogencore-linux.azurewebsites.net/?name=create-build-pipeline) - Asp.Net Core

Importing repository from GitHub

---

src/AzureDevOpsDemoBuilder/Services/ExtractorService.cs
src/AzureDevOpsRestApi/Extractor/GetWorkItemsCount.cs

Creating endpoint to import repo from GitHub

formatting the import Github repo Json

---

src/VstsDemoBuilder/Templates/WVDGuidance/WorkItems/Task.json
src/VstsDemoBuilder/Templates/WVDGuidance/WorkItems/User Story.json

[AB#3531](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3531)

updated task and story for WVD Governance

---

src/VstsDemoBuilder/Services/ExtractorService.cs
src/VstsRestAPI/Viewmodel/Extractor/GetServiceEndpoints.cs

adding Managed Group service connection

---

src/VstsDemoBuilder/Services/ExtractorService.cs
src/VstsDemoBuilder/Services/ProjectService.cs

[AB#3656](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3656)

fixed yml pipeline issue

---

src/VstsDemoBuilder/Templates/TemplateSetting.json
src/VstsRestAPI/Extractor/GetWorkItemsCount.cs

[AB#3732](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3732) [AB#3735](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3735)

added note for MS learn templates

---

src/VstsDemoBuilder/Templates/UnifiedDataGovernance/WorkItems/Epic.json
src/VstsDemoBuilder/Templates/UnifiedDataGovernance/WorkItems/Feature.json
src/VstsDemoBuilder/Templates/UnifiedDataGovernance/WorkItems/Task.json
src/VstsDemoBuilder/Templates/UnifiedDataGovernance/WorkItems/User Story.json
src/VstsRestAPI/Extractor/GetWorkItemsCount.cs
src/VstsRestAPI/Viewmodel/Extractor/GetWorkItemsResponse.cs

- Updating work item order [AB#3742](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3742)
- Fixing work fetch item order [AB#2743](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/2743)

UdG template update

---

src/AzureDevOpsDemoBuilder/Controllers/EnvironmentController.cs
src/AzureDevOpsDemoBuilder/Controllers/GitHubController.cs
src/AzureDevOpsDemoBuilder/Models/Project.cs
src/AzureDevOpsDemoBuilder/Services/ProjectService.cs
src/AzureDevOpsDemoBuilder/Views/Environment/CreateProject.cshtml
src/AzureDevOpsDemoBuilder/wwwroot/Scripts/AppScripts/GitHubAuth.js
src/AzureDevOpsDemoBuilder/wwwroot/Scripts/AppScripts/create.js
src/AzureDevOpsDemoBuilder/wwwroot/Templates/CreateGitHubRepo.json
src/AzureDevOpsRestApi/Git/GitHubImportRepo.cs
src/AzureDevOpsRestApi/Git/ImportRepoResponse.cs
src/AzureDevOpsRestApi/Viewmodel/GitHub/GitHubSecrets.cs

[AB#3749](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3749)
mapping the imported repo to pipeline.
replacing build agents in runtime

importing repo to user or orgs

---

src/VstsDemoBuilder/Templates/Keyvault/ReleaseDefinitions/SmartHotel-CouponManagement-CD.json

[AB#3820](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3820)

fixed azure-keyvault CD issue

---

src/VstsDemoBuilder/Templates/LaunchDarkly/BuildDefinitions/LaunchDarkly.json
src/VstsDemoBuilder/Templates/PHP/BuildDefinitions/PHP.json
src/VstsDemoBuilder/Templates/PartsUnlimited-YAML/ImportSourceCode/PartsUnlimited.json
src/VstsDemoBuilder/Templates/PartsUnlimited-YAML/ServiceEndpoints/PartsUnlimited-code.json
src/VstsDemoBuilder/Templates/PartsUnlimited/BuildDefinitions/PartsUnlimitedE2E.json
src/VstsDemoBuilder/Templates/Python/BuildDefinitions/Python.json
src/VstsDemoBuilder/Templates/ReleaseGates/BuildDefinitions/PartsUnlimited-CI.json
src/VstsDemoBuilder/Templates/SonarQube/BuildDefinitions/SonarQube.json
src/VstsDemoBuilder/Templates/Terraform/BuildDefinitions/Terraform.json
src/VstsDemoBuilder/Templates/WhiteSource-Bolt/BuildDefinitions/WhiteSourceBolt.json
src/VstsDemoBuilder/Templates/WhiteSource-Bolt/ImportSourceCode/WebGoat.json
src/VstsDemoBuilder/Templates/WhiteSource-Bolt/ServiceEndpoints/WebGoat-code.json

[AB#3824](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3824)
[AB#3825](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3825)
[AB#3826](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3826)
[AB#3827](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3827)
[AB#3828](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3828)
[AB#3830](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3830)
[AB#3832](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3832)

Fixed PartsUnlimited Build pipeline

---

src/VstsDemoBuilder/Templates/Selenium/BuildDefinitions/Selenium.json

selenium agent change

---

src/VstsDemoBuilder/Templates/DL-Python/ReleaseDefinitions/Python-CD.json

[AB#3880](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3880)
closes #746

python release template fix

---

src/VstsDemoBuilder/Templates/DL-WhiteSource-Bolt/Dashboard/Dashboard.json
src/VstsDemoBuilder/Templates/DL-WhiteSource-Bolt/Extensions.json
src/VstsDemoBuilder/Templates/DoJoWhiteBeltGold/Extensions.json

Extension name changes

---

src/VstsDemoBuilder/Services/ProjectService.cs
src/VstsDemoBuilder/Templates/DL-Docker/Dashboard/Dashboard.json

fixed dashboard creation fixes #947 resolves #940

fixed dashboard creation fixes #947
